server:
    port: 80
    contextPath: /turbo

# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: fe5293fdb886c08d6119d39951370c064bc0fde6

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: trainer@localhost

    messageSource:
        cacheSeconds: 1

    thymeleaf:
        mode: XHTML
        cache: false
        prefix: classpath:/_framework/templates/

    freemarker:
        check-template-location: false

swagger:
    title: trainer API
    description: trainer applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

esearch:
    host: localhost
    port: 9300

liquibase:
    root:   D:\Workspace\#liquibase\angular2webpack
    check-change-log-location: false
